#!/usr/bin/env bash

# from https://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

java -Xmx1G -cp "$SCRIPTPATH/src" RandSim "$@"
